import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class InvoiceCreate {
  @ApiProperty()
  invoice_number: string;
  @ApiProperty()
  issue_date: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  amount: number;
  @ApiProperty()
  status: string;
}

export class Invoice {
  @ApiProperty()
  id: number;
  @ApiProperty()
  invoice_number: string;
  @ApiProperty()
  issue_date: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  amount: number;
  @ApiProperty()
  status: string;
}
