/**
 * This file generated by Apso.
 */
import { InvoiceModule } from './Invoice/Invoice.module';
import { PaymentModule } from './Payment/Payment.module';

export default [InvoiceModule, PaymentModule];
