import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PaymentCreate {
  @ApiProperty()
  payment_date: string;
  @ApiProperty()
  amount: number;
  @ApiProperty()
  status: string;
}

export class Payment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  payment_date: string;
  @ApiProperty()
  amount: number;
  @ApiProperty()
  status: string;
}
